function dxin_dxi0 = jacobian_points_n_points_0(sn1,sn2,sn3)
%JACOBIAN_POINTS_N_POINTS_0
%    DXIN_DXI0 = JACOBIAN_POINTS_N_POINTS_0(SN1,SN2,SN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    15-Jan-2020 12:19:31

t2 = sparse(sn1.^2);
t3 = sparse(sn1.^3);
t4 = sparse(sn2.^2);
t5 = sparse(sn2.^3);
t6 = sparse(sn3.^2);
t7 = sparse(sn3.^3);
t8 = sparse(sn1.*sn2.*2.0);
t9 = sparse(sn1.*sn3.*2.0);
t10 = sparse(sn2.*sn3.*2.0);
t11 = sparse(-sn1);
t12 = sparse(-sn2);
t13 = sparse(-sn3);
t14 = sparse(sn1.*t4);
t15 = sparse(sn2.*t2);
t16 = sparse(sn1.*t6);
t17 = sparse(sn3.*t2);
t18 = sparse(sn2.*t6);
t19 = sparse(sn3.*t4);
t20 = sparse(t2.*8.0);
t21 = sparse(t4.*8.0);
t22 = sparse(t6.*8.0);
t23 = sparse(t2+t4+t6+1.0);
t24 = sparse(1.0./t23.^2);
dxin_dxi0 = sparse([1,2,3,1,2,3,1,2,3],[1,1,1,2,2,2,3,3,3],[-t24.*(t21+t22)+1.0,t24.*(t7-t8+t13+t17+t19).*-4.0,t24.*(t5+t9+t12+t15+t18).*4.0,t24.*(t7+t8+t13+t17+t19).*4.0,-t24.*(t20+t22)+1.0,t24.*(t3-t10+t11+t14+t16).*-4.0,t24.*(t5-t9+t12+t15+t18).*-4.0,t24.*(t3+t10+t11+t14+t16).*4.0,-t24.*(t20+t21)+1.0],3,3);
