function partials = STM_nerm(df,dr,mu,r,x,y,z)
%STM_NERM
%    PARTIALS = STM_NERM(DF,DR,MU,R,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    29-Oct-2019 10:04:12

t2 = sparse(r+x);
t3 = sparse(t2.^2);
t4 = sparse(y.^2);
t5 = sparse(z.^2);
t6 = sparse(t3+t4+t5);
t7 = sparse(1.0./t6.^(5.0./2.0));
t8 = sparse(1.0./r);
t9 = sparse(r.*2.0);
t10 = sparse(x.*2.0);
t11 = sparse(t9+t10);
t12 = sparse(df.^2);
t13 = sparse(1.0./t6.^(3.0./2.0));
t14 = sparse(df.*2.0);
t15 = sparse(mu.*t7.*y.*z.*3.0);
partials = sparse([4,5,6,4,5,6,4,5,6,1,5,2,4,3],[1,1,1,2,2,2,3,3,3,4,4,5,5,6],[t12-mu.*t13+mu.*t2.*t7.*t11.*(3.0./2.0),df.*dr.*t8.*2.0+mu.*t7.*t11.*y.*(3.0./2.0),mu.*t7.*t11.*z.*(3.0./2.0),df.*dr.*t8.*-2.0+mu.*t2.*t7.*y.*3.0,t12-mu.*t13+mu.*t4.*t7.*3.0,t15,mu.*t2.*t7.*z.*3.0,t15,-mu.*t7.*(t4-t5.*2.0+r.*x.*2.0+r.^2+x.^2),1.0,-t14,1.0,t14,1.0],6,6);
