function partials = STM_MRP(s1,s2,s3,wx,wy,wz)
%STM_MRP
%    PARTIALS = STM_MRP(S1,S2,S3,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Nov-2019 18:31:51

t2 = sparse((s1.*s2)./2.0);
t3 = sparse(s1.^2);
t4 = sparse(t3./4.0);
t5 = sparse(s2.^2);
t6 = sparse(s3.^2);
t7 = sparse(wz./2.0);
t8 = sparse((s1.*wy)./2.0);
t9 = sparse((s1.*wx)./2.0);
t10 = sparse((s2.*wy)./2.0);
t11 = sparse((s3.*wz)./2.0);
t12 = sparse(t9+t10+t11);
t13 = sparse(s2./2.0);
t14 = sparse((s1.*s3)./2.0);
t15 = sparse((s2.*s3)./2.0);
t16 = sparse(t5./4.0);
t17 = sparse((s1.*wz)./2.0);
t18 = sparse(wx./2.0);
t19 = sparse((s2.*wz)./2.0);
partials = sparse([1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3],[1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6],[t4-t5./4.0-t6./4.0+1.0./4.0,s3./2.0+t2,-t13+t14,s3.*(-1.0./2.0)+t2,-t4-t6./4.0+t16+1.0./4.0,s1./2.0+t15,t13+t14,s1.*(-1.0./2.0)+t15,-t4+t6./4.0-t16+1.0./4.0,t12,-t7-t8+(s2.*wx)./2.0,-t17+wy./2.0+(s3.*wx)./2.0,t7+t8-(s2.*wx)./2.0,t12,-t18-t19+(s3.*wy)./2.0,t17-wy./2.0-(s3.*wx)./2.0,t18+t19-(s3.*wy)./2.0,t12],3,6);
